VARIABLE_NAMES = [
    "sea_ice_concentration_01",
    "sea_ice_concentration_02",
    "sea_ice_concentration_03",
    "sea_ice_concentration_04",
    "sea_ice_concentration_05",
    "sea_ice_concentration_06",
    "sea_ice_concentration_07",
    "sea_ice_concentration_09",
    "sea_ice_concentration_10",
    "sea_ice_concentration_11",
    "sea_ice_concentration_12",
    "linear_trend_sic_forecast_01",
    "linear_trend_sic_forecast_02",
    "linear_trend_sic_forecast_03",
    "linear_trend_sic_forecast_04",
    "linear_trend_sic_forecast_05",
    "linear_trend_sic_forecast_06",
    "2m_air_temp_anom_01",
    "2m_air_temp_anom_02",
    "2m_air_temp_anom_03",
    "500hp_air_temp_anom_01",
    "500hp_air_temp_anom_02",
    "500hp_air_temp_anom_03",
    "sea_surface_temp_anom_01",
    "sea_surface_temp_anom_02",
    "sea_surface_temp_anom_03",
    "downwelling_solar_rad_anom_01",
    "downwelling_solar_rad_anom_02",
    "downwelling_solar_rad_anom_03",
    "upwelling_solar_rad_anom_01",
    "upwelling_solar_rad_anom_02",
    "upwelling_solar_rad_anom_03",
    "sea_level_pressure_anom_01",
    "sea_level_pressure_anom_02",
    "sea_level_pressure_anom_03",
    "500hp_geopotential_height_anom_01",
    "500hp_geopotential_height_anom_02",
    "500hp_geopotential_height_anom_03",
    "150hp_geopotential_height_anom_01",
    "150hp_geopotential_height_anom_02",
    "150hp_geopotential_height_anom_03",
    "10hp_zonal_wind_speed_01",
    "10hp_zonal_wind_speed_02",
    "10hp_zonal_wind_speed_03",
    "x_wind_01",
    "y_wind_01",
    "land_mask",
    "cos_init_month",
    "sin_init_month",
]

DATA_PATHS = [
    "test_data/test_data_batch_0_w_dates.npz",
    "test_data/test_data_batch_20_w_dates.npz",
    "test_data/test_data_batch_23_w_dates.npz",
    "icenet/experimental/test_data/test_data_batch_0.npz",
    "experimental/test_data/test_data_batch_1.npz",
    "experimental/test_data/test_data_batch_2.npz",
    "experimental/test_data/test_data_batch_3.npz",
    "experimental/test_data/test_data_batch_4.npz",
]

LAND_MASK_PATH = "data/masks/land_mask.npy"
REGION_MASK_PATH = "data/masks/region_mask.npy"
MODEL_PATH = "icenet/experimental/trained_models/network_dropout_mc_50.h5"
